export RMQ_HOST='localhost'
export RMQ_PORT='5672'
export RMQ_MONITOR_PORT='15672'
export RMQ_USERNAME='alpesh'
export RMQ_PASSWORD='alpesh123'
export RMQ_HEARTBEATS='30'
export RMQ_PRIMARY_EXCHANGE='primaryExchange'